# 数组属性方法汇总图

||作用|
|-|-|
|1|**基本属性**
|`a.dtype`|数组元素类型 `float32,uint8,...`
|`a.shape`|数组形状 `(m,n,o,...)`
|`a.size`|数组元素数
|`a.itemsize`|每个元素占字节数
|`a.nbytes`|所有元素占的字节
|`a.ndim`|数组维度
|2|**形状相关**
|`a.flat`|所有元素的迭代器
|`a.flatten()`|返回一个1维数组的复制
|`a.ravel()`|返回一个1维数组，高效
|`a.resize(new_size)`|改变形状
|`a.swapaxes(axis1, axis2)`|交换两个维度的位置
|`a.transpose(*axex)`|交换所有维度的位置
|`a.T`|转置，`a.transpose()`
|`a.squeeze()`| 去除所有长度为1的维度
|3|**填充复制**
|`a.copy()`| 返回数组的一个复制
|`a.fill(value)`| 将数组的元组设置为特定值
|4|**转化**
|`a.tolist()`|将数组转化为列表
|`a.tostring()`|转换为字符串
|`a.astype(dtype)`|转化为指定类型
|`a.byteswap(False)`|转换大小字节序
|`a.view(type_or_dtype)`|生成一个使用相同内存，但使用不同的表示方法的数组
|5|**复数**
|`a.imag`|虚部
|`a.real`|实部
|`a.conjugate()`|复共轭
|`a.conj()`|复共轭（缩写）
|6|**保存**
|`a.dump(file)`|将二进制数据存在file中
|`a.dump()`|将二进制数据表示成字符串
|`a.tofile(fid, sep="",format="%s")`|格式化ASCⅡ码写入文件
|7|**查找排序**
|`a.nonzero()`|返回所有非零元素的索引
|`a.sort(axis=-1)`|沿某个轴排序
|`a.argsort(axis=-1)`|沿某个轴，返回按排序的索引
|`a.searchsorted(b)`|返回将b中元素插入a后能保持有序的索引值
|8|**元素数学操作**
|`a.clip(low, high)`|将数值限制在一定范围内
|`a.round(decimals=0)`|近似到指定精度
|`a.cumsum(axis=None)`|累加和
|`a.cumprod(axis=None)`|累乘积
|9|**约简操作**
|`a.sum(axis=None)`|求和
|`a.prod(axis=None)`|求积
|`a.min(axis=None)`|最小值
|`a.max(axis=None)`|最大值
|`a.argmin(axis=None)`|最小值索引
|`a.argmax(axis=None)`|最大值索引
|`a.ptp(axis=None)`|最大值减最小值
|`a.mean(axis=None)`|平均值
|`a.std(axis=None)`|标准差
|`a.var(axis=None)`|方差
|`a.any(axis=None)`|只要有一个不为0，返回真，逻辑或
|`a.all(axis=None)`|所有都不为0，返回真，逻辑与

# 数组操作示例

In [17]:
from numpy import *
import numpy as np

a = array([1,2,3,4,5])

type(a)

numpy.ndarray

数据类型

In [18]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [19]:
# 数组类型（所有元素都为int64）
a.dtype

dtype('int64')

In [20]:
# 每个元素占的字节
a.itemsize

8

In [21]:
# 查看形状，会返回一个元组，每个元素代表这一维的元素数目：
a.shape 

(5,)

In [22]:
shape(a)

(5,)

In [23]:
# 查看元素数目
a.size

5

# 数组初始化

In [24]:
# fill填充
a.fill(-8)
a

array([-8, -8, -8, -8, -8])

In [27]:
# 全0矩阵
a1 = np.zeros((2,3))
a1

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
# 全1矩阵
a1 = np.ones((2,3))
a1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [31]:
# 对角矩阵（对角为1）
a1 = np.eye(3)
a1

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [39]:
# 普通对角矩阵
a2 = np.diag((1,3,5,7))
a2

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

# 多维数组

In [48]:
a = array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a.shape

(3, 3)

In [50]:
# 多维数组索引（第二行第三个元素）
a[1,2]

6

In [52]:
# 获取第二行
a[1,:]

array([4, 5, 6])

In [54]:
# 生成等差数组（初始值为2，每次增加10， 直到 <= 50）
a = arange(2, 50, 10)
a

array([ 2, 12, 22, 32, 42])

# 多维数组及索引

In [57]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [58]:
y = a[:,:,[2, -1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

# where语句

In [61]:
# where返回满足条件的数组
a = array([-3,-5,-7,0,1,2,5,8])
y = where(a>0)
y

(array([4, 5, 6, 7]),)