In [1]:
from numpy import *
import numpy as np

In [15]:
a = array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 求和

In [8]:
# 求和
y = sum(a)
# 或者 y = a.sum()
y

45

In [11]:
# 指定维求和(第一维)
y = sum(a, axis=0)
y

array([12, 15, 18])

In [14]:
# 指定维求和(第2维)
y = sum(a, axis=1)
y

array([ 6, 15, 24])

# 乘积

In [19]:
a = array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [20]:
a.prod()

24

# 最大最小值

In [22]:
a.min()

1

In [23]:
a.max()

4

In [24]:
# 最小值，所在位置
a.argmin()

0

In [25]:
# 最大值，所在位置
a.argmax()

3

In [26]:
# 均值
a.mean()

2.5

# 标准差

In [27]:
a.std()

1.1180339887498949