# Numpy简介

Numpy是Python的一个很重要的第三方库，很多其他科学计算的第三方库都是以Numpy为基础建立的。

Numpy的一个重要特性是它的数组计算。

## 导入numpy包

In [5]:
import numpy as np

## 数组操作

python列表不是直接操作

In [13]:
a = [1,2,3,4,5]
a+1



TypeError: can only concatenate list (not "int") to list

使用np数组

In [16]:
a = np.array([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

np数据相乘

In [25]:
from numpy import array
b = array([1,2,3])
c = array([1,2,2])
#  相加
print(b + c)
# 相乘
print(b * c)
# 乘方
print(b ** c)

[2 4 5]
[1 4 6]
[1 4 9]


np数据shape

In [34]:
a = np.array([1,2,3,4,5,6,7,8])
a.shape
# (8,) 表示8列0行

(8,)

修改shape

In [32]:
a.shape= 2,4
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
a.shape # 2行4列

(8,)

In [38]:
a.shape= 4,2
a # 修改为4行2列

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

linspace生成等间隔数据

In [71]:
a = np.linspace(0, 3, 21)
a

array([ 0.  ,  0.15,  0.3 ,  0.45,  0.6 ,  0.75,  0.9 ,  1.05,  1.2 ,
        1.35,  1.5 ,  1.65,  1.8 ,  1.95,  2.1 ,  2.25,  2.4 ,  2.55,
        2.7 ,  2.85,  3.  ])

In [72]:
b = np.sin(a)
b

array([ 0.   ,  0.149,  0.296,  0.435,  0.565,  0.682,  0.783,  0.867,
        0.932,  0.976,  0.997,  0.997,  0.974,  0.929,  0.863,  0.778,
        0.675,  0.558,  0.427,  0.287,  0.141])

array([ True,  True,  True, False, False, False,  True,  True], dtype=bool)