使用 mat 方法将 2 维数组转化为矩阵：

In [2]:
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
a

array([[1, 2, 4],
       [2, 5, 3],
       [7, 8, 9]])

In [3]:
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [4]:
# 构造一个矩阵
A = np.mat('1,2,4; 2,5,3; 7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [5]:
# 利用分块创造新的矩阵：
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [6]:
# 矩阵与向量乘法
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [7]:
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [8]:
A * x

matrix([[17],
        [21],
        [50]])

In [9]:
# 求逆矩阵

In [10]:
A.I

matrix([[-0.42857143, -0.28571429,  0.28571429],
        [-0.06122449,  0.3877551 , -0.10204082],
        [ 0.3877551 , -0.12244898, -0.02040816]])