In [2]:
from numpy import *
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape=2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
a.shape=3,2
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

# newaxis 增加数组维数

In [6]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
shape(a)

(3, 2)

In [10]:
# 增加一个维度
y = a[newaxis,:]
y

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [11]:
shape(y)

(1, 3, 2)

# 数组转置

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
shape(a)

(3, 2)

In [19]:
b = a.transpose()
b

array([[0, 2, 4],
       [1, 3, 5]])

In [20]:
b.shape

(2, 3)

# 数组连接

In [22]:
a = array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b = array([[7,8,9],[3,3,3]])
b

array([[7, 8, 9],
       [3, 3, 3]])

In [28]:
y = concatenate((a,b))
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 3, 3]])

In [31]:
# 沿着第一维(列)进行连接
y = concatenate((a,b),axis=0)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 3, 3]])

In [32]:
# 沿着第二维(行)进行连接
y = concatenate((a,b),axis=1)
y

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 3, 3, 3]])

# 多维->1维

In [34]:
y.flatten()

array([1, 2, 3, 7, 8, 9, 4, 5, 6, 3, 3, 3])

In [36]:
# 返回一个迭代器
b = y.flat
b

In [37]:
b[0]

1

In [38]:
b[1]

2