In [4]:
from numpy import *
import numpy as np
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


# 数组排序

In [2]:
a = array([1,-1,3,5,-3,7,-8])
sort(a)

array([-8, -3, -1,  1,  3,  5,  7])

In [3]:
# 返回位置索引
argsort(a)

array([6, 4, 1, 0, 2, 3, 5])

# 二维数组排序

In [10]:
a = array([[1,3,2],[9,8,7],[6,5,4]])
a

array([[1, 3, 2],
       [9, 8, 7],
       [6, 5, 4]])

In [11]:
# 默认对每一行进行排序
sort(a)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [12]:
# 默认对第一维（每一列进行排序）
sort(a,axis=0)

array([[1, 3, 2],
       [6, 5, 4],
       [9, 8, 7]])

In [14]:
# 默认对第二维（每一行进行排序）
sort(a,axis=1)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])